import type { FileClass } from '../model.js';
import { basename, extname, globToRegExp, normalizePath, segments } from '../util/paths.js';

export const LANGUAGES: Record<string, string> = {
  '.ts': 'TypeScript', '.tsx': 'TypeScript', '.mts': 'TypeScript', '.cts': 'TypeScript',
  '.js': 'JavaScript', '.jsx': 'JavaScript', '.mjs': 'JavaScript', '.cjs': 'JavaScript',
  '.py': 'Python', '.pyi': 'Python', '.ipynb': 'Jupyter Notebook',
  '.go': 'Go', '.rs': 'Rust', '.java': 'Java', '.kt': 'Kotlin', '.kts': 'Kotlin', '.scala': 'Scala',
  '.rb': 'Ruby', '.php': 'PHP', '.cs': 'C#', '.fs': 'F#', '.vb': 'Visual Basic',
  '.c': 'C', '.h': 'C/C++ Header', '.cc': 'C++', '.cpp': 'C++', '.cxx': 'C++', '.hpp': 'C++', '.hh': 'C++',
  '.m': 'Objective-C', '.mm': 'Objective-C++', '.swift': 'Swift', '.dart': 'Dart',
  '.ex': 'Elixir', '.exs': 'Elixir', '.erl': 'Erlang', '.clj': 'Clojure', '.hs': 'Haskell', '.ml': 'OCaml',
  '.lua': 'Lua', '.pl': 'Perl', '.r': 'R', '.jl': 'Julia', '.sol': 'Solidity', '.zig': 'Zig', '.nim': 'Nim',
  '.sh': 'Shell', '.bash': 'Shell', '.zsh': 'Shell', '.ps1': 'PowerShell',
  '.sql': 'SQL', '.graphql': 'GraphQL', '.gql': 'GraphQL', '.proto': 'Protocol Buffers',
  '.html': 'HTML', '.htm': 'HTML', '.css': 'CSS', '.scss': 'SCSS', '.sass': 'Sass', '.less': 'Less',
  '.vue': 'Vue', '.svelte': 'Svelte', '.astro': 'Astro',
  '.tf': 'HCL', '.hcl': 'HCL', '.yaml': 'YAML', '.yml': 'YAML', '.json': 'JSON', '.toml': 'TOML', '.xml': 'XML',
  '.md': 'Markdown', '.mdx': 'MDX', '.rst': 'reStructuredText',
};

const CODE_LANGS = new Set(
  Object.values(LANGUAGES).filter((l) => !['YAML', 'JSON', 'TOML', 'XML', 'Markdown', 'MDX', 'reStructuredText'].includes(l)),
);

export function languageOf(path: string): string | undefined {
  const b = basename(path);
  if (b === 'Dockerfile' || b.startsWith('Dockerfile.') || b.endsWith('.dockerfile')) return 'Dockerfile';
  if (b === 'Makefile' || b === 'makefile' || b === 'GNUmakefile') return 'Makefile';
  return LANGUAGES[extname(path)];
}

export function isCodeLanguage(lang: string | undefined): boolean {
  return !!lang && (CODE_LANGS.has(lang) || lang === 'Dockerfile' || lang === 'Makefile');
}

const LOCKFILES = new Set([
  'package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lock', 'bun.lockb',
  'poetry.lock', 'Pipfile.lock', 'uv.lock', 'pdm.lock', 'go.sum', 'Cargo.lock', 'Gemfile.lock',
  'composer.lock', 'packages.lock.json', 'gradle.lockfile', 'Package.resolved', 'pubspec.lock', 'mix.lock',
]);

const MANIFESTS = new Set([
  'package.json', 'pyproject.toml', 'Pipfile', 'setup.py', 'setup.cfg', 'go.mod', 'Cargo.toml', 'Gemfile',
  'composer.json', 'pom.xml', 'build.gradle', 'build.gradle.kts', 'Package.swift', 'pubspec.yaml', 'mix.exs',
]);

export function isManifest(path: string): boolean {
  const b = basename(path);
  return MANIFESTS.has(b) || /^requirements([-_.].*)?\.(txt|in)$/i.test(b) || b.endsWith('.csproj');
}

export function isLockfile(path: string): boolean {
  return LOCKFILES.has(basename(path));
}

const VENDOR_SEGMENTS = new Set(['vendor', 'vendored', 'third_party', 'third-party', 'thirdparty', 'node_modules', 'bower_components', 'Pods']);

/** Root directory of vendored code containing this path, if any. */
export function vendoredRoot(path: string): string | null {
  const segs = segments(path);
  for (let i = 0; i < segs.length - 1; i++) {
    if (VENDOR_SEGMENTS.has(segs[i]!)) return segs.slice(0, i + 1).join('/');
    if (segs[i] === 'Carthage' && segs[i + 1] === 'Checkouts') return segs.slice(0, i + 2).join('/');
  }
  return null;
}

const BUILD_OUTPUT_DIRS = new Set(['dist', 'build', 'out', '.next', '.nuxt', 'target', 'obj', 'coverage', '__pycache__', '.svelte-kit', '.output']);

export function buildOutputDir(path: string): string | null {
  const segs = segments(path);
  for (let i = 0; i < segs.length - 1; i++) if (BUILD_OUTPUT_DIRS.has(segs[i]!)) return segs.slice(0, i + 1).join('/');
  return null;
}

const GENERATED_NAME = [
  /\.pb\.(go|cc|h|swift)$/, /_pb2(_grpc)?\.pyi?$/, /\.pb\.gw\.go$/, /_grpc\.pb\.go$/, /\.g\.dart$/, /\.freezed\.dart$/,
  /\.designer\.cs$/i, /[._-]generated\.[a-z]+$/i, /\.min\.(js|css|mjs)$/, /\.(js|css|mjs)\.map$/, /\.bundle\.js$/,
  /(^|\/)__generated__\//, /(^|\/)generated\//,
];

export function generatedByName(path: string): boolean {
  return GENERATED_NAME.some((re) => re.test(path));
}

const GENERATED_HEADER = [
  /Code generated .* DO NOT EDIT\.?/,
  /@generated\b/,
  /\bDO NOT EDIT\b.*\b(generated|autogenerated)\b/i,
  /\b(auto-?generated|automatically generated|machine generated) (file|code|by)\b/i,
  /This file (was|is) (auto(matically)?[- ]?)?generated/i,
  /Generated by the protocol buffer compiler/,
  /Autogenerated by Thrift/,
  /generated by (?:swagger|openapi)-codegen/i,
  /<auto-generated\s*\/?>/i,
];

/** Marker text if the first lines of a file declare it generated. */
export function generatedHeaderMarker(text: string): string | null {
  const head = text.slice(0, 2048).split('\n').slice(0, 12);
  for (const line of head) {
    // "Generated by ChatGPT/Claude/Copilot" is a statement about AI authorship, not tool-generated code.
    if (/\b(chatgpt|gpt-?\d|claude|copilot|gemini|cursor|devin|codex|an? ai\b|ai assistant|llm)\b/i.test(line)) continue;
    for (const re of GENERATED_HEADER) {
      const m = re.exec(line);
      if (m) return m[0];
    }
  }
  return null;
}

/** Minified JS/CSS: few very long lines. */
export function looksMinified(path: string, text: string): boolean {
  const e = extname(path);
  if (!['.js', '.mjs', '.cjs', '.css'].includes(e) || text.length < 2048) return false;
  const lines = text.split('\n');
  const longLines = lines.filter((l) => l.length > 1000).length;
  return longLines > 0 && text.length / Math.max(lines.length, 1) > 300;
}

const TEST_PATTERNS = [
  /(^|\/)(tests?|__tests__|spec|specs|e2e|testdata|test_data|fixtures?)\//i,
  /\.(test|spec)\.[a-z0-9]+$/i,
  /(^|\/)test_[^/]+\.py$/,
  /_test\.(go|py|rb|exs)$/,
  /Tests?\.(java|kt|cs|swift)$/,
];

export function isTestPath(path: string): boolean {
  return TEST_PATTERNS.some((re) => re.test(path));
}

export function isDocsPath(path: string): boolean {
  const e = extname(path);
  return /(^|\/)docs?\//i.test(path) || ['.md', '.mdx', '.rst', '.adoc', '.txt'].includes(e);
}

const CONFIG_EXT = new Set(['.yaml', '.yml', '.json', '.toml', '.ini', '.cfg', '.conf', '.env', '.properties', '.xml']);

export type BinaryKind = 'executable' | 'library' | 'archive' | 'bytecode' | 'model_weights' | 'data' | 'asset' | 'unknown';

const BINARY_EXT: Record<string, BinaryKind> = {
  '.exe': 'executable', '.bin': 'executable', '.elf': 'executable', '.app': 'executable', '.msi': 'executable',
  '.dll': 'library', '.so': 'library', '.dylib': 'library', '.a': 'library', '.lib': 'library', '.o': 'library', '.node': 'library',
  '.jar': 'archive', '.war': 'archive', '.ear': 'archive', '.zip': 'archive', '.tar': 'archive', '.gz': 'archive', '.tgz': 'archive',
  '.whl': 'archive', '.egg': 'archive', '.nupkg': 'archive', '.apk': 'archive', '.aab': 'archive', '.ipa': 'archive', '.dmg': 'archive',
  '.7z': 'archive', '.rar': 'archive', '.xz': 'archive', '.bz2': 'archive', '.gem': 'archive', '.deb': 'archive', '.rpm': 'archive',
  '.class': 'bytecode', '.pyc': 'bytecode', '.pyo': 'bytecode', '.wasm': 'bytecode', '.dex': 'bytecode',
  '.pt': 'model_weights', '.pth': 'model_weights', '.onnx': 'model_weights', '.safetensors': 'model_weights', '.h5': 'model_weights',
  '.ckpt': 'model_weights', '.gguf': 'model_weights', '.pb': 'model_weights', '.tflite': 'model_weights', '.mlmodel': 'model_weights', '.joblib': 'model_weights', '.pkl': 'model_weights',
  '.db': 'data', '.sqlite': 'data', '.sqlite3': 'data', '.parquet': 'data', '.npy': 'data', '.npz': 'data', '.feather': 'data', '.avro': 'data',
  '.png': 'asset', '.jpg': 'asset', '.jpeg': 'asset', '.gif': 'asset', '.ico': 'asset', '.webp': 'asset', '.bmp': 'asset', '.tiff': 'asset',
  '.woff': 'asset', '.woff2': 'asset', '.ttf': 'asset', '.otf': 'asset', '.eot': 'asset', '.mp3': 'asset', '.mp4': 'asset', '.wav': 'asset',
  '.webm': 'asset', '.mov': 'asset', '.ogg': 'asset', '.pdf': 'asset', '.psd': 'asset', '.sketch': 'asset', '.fig': 'asset',
};

export function binaryKindByName(path: string): BinaryKind | null {
  return BINARY_EXT[extname(path)] ?? null;
}

export function binaryKindByMagic(head: Uint8Array): BinaryKind | null {
  if (head.length >= 4 && head[0] === 0x7f && head[1] === 0x45 && head[2] === 0x4c && head[3] === 0x46) return 'executable'; // ELF
  if (head.length >= 2 && head[0] === 0x4d && head[1] === 0x5a) return 'executable'; // PE "MZ"
  if (head.length >= 4) {
    const m = ((head[0]! << 24) | (head[1]! << 16) | (head[2]! << 8) | head[3]!) >>> 0;
    if ([0xfeedface, 0xfeedfacf, 0xcefaedfe, 0xcffaedfe, 0xcafebabe].includes(m)) return m === 0xcafebabe ? 'bytecode' : 'executable';
  }
  if (head.length >= 4 && head[0] === 0x50 && head[1] === 0x4b && head[2] === 0x03 && head[3] === 0x04) return 'archive';
  if (head.length >= 4 && head[0] === 0x00 && head[1] === 0x61 && head[2] === 0x73 && head[3] === 0x6d) return 'bytecode'; // wasm
  return null;
}

/** Coding-agent configuration files: corroborating evidence that a tool was used in this repository. */
export const AGENT_CONFIG: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /(^|\/)CLAUDE(\.local)?\.md$/, tool: 'claude-code' },
  { pattern: /(^|\/)\.claude\//, tool: 'claude-code' },
  { pattern: /(^|\/)AGENTS\.md$/, tool: 'agents-md' },
  { pattern: /(^|\/)\.cursor\/(rules|mcp\.json)/, tool: 'cursor' },
  { pattern: /(^|\/)\.cursorrules$/, tool: 'cursor' },
  { pattern: /(^|\/)\.cursorignore$/, tool: 'cursor' },
  { pattern: /^\.github\/copilot-instructions\.md$/, tool: 'github-copilot' },
  { pattern: /^\.github\/instructions\/.+\.instructions\.md$/, tool: 'github-copilot' },
  { pattern: /^\.github\/prompts\/.+\.prompt\.md$/, tool: 'github-copilot' },
  { pattern: /(^|\/)\.windsurfrules$/, tool: 'windsurf' },
  { pattern: /(^|\/)\.windsurf\//, tool: 'windsurf' },
  { pattern: /(^|\/)\.clinerules/, tool: 'cline' },
  { pattern: /(^|\/)\.roo\//, tool: 'roo-code' },
  { pattern: /(^|\/)\.aider[^/]*$/, tool: 'aider' },
  { pattern: /(^|\/)GEMINI\.md$/, tool: 'gemini-cli' },
  { pattern: /(^|\/)\.gemini\//, tool: 'gemini-cli' },
  { pattern: /(^|\/)\.continue\//, tool: 'continue' },
  { pattern: /(^|\/)\.continuerc\.json$/, tool: 'continue' },
  { pattern: /(^|\/)\.amazonq\//, tool: 'amazon-q' },
  { pattern: /(^|\/)\.junie\//, tool: 'junie' },
  { pattern: /(^|\/)\.kiro\//, tool: 'kiro' },
  { pattern: /(^|\/)opencode\.jsonc?$/, tool: 'opencode' },
  { pattern: /(^|\/)\.codex\//, tool: 'openai-codex' },
  { pattern: /(^|\/)\.devin\//, tool: 'devin' },
  { pattern: /(^|\/)\.mcp\.json$/, tool: 'mcp-client' },
];

export function agentConfigTool(path: string): string | null {
  for (const { pattern, tool } of AGENT_CONFIG) if (pattern.test(path)) return tool;
  return null;
}

export function isAgentTraceFile(path: string): boolean {
  return /(^|\/)\.agent-trace\/.+\.(json|jsonl)$/.test(path) || /(^|\/)[^/]*\.agent-trace\.json$/.test(path);
}

export interface Gitattributes {
  generated: RegExp[];
  vendored: RegExp[];
  documentation: RegExp[];
  notGenerated: RegExp[];
}

export function parseGitattributes(text: string): Gitattributes {
  const out: Gitattributes = { generated: [], vendored: [], documentation: [], notGenerated: [] };
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const [pattern, ...attrs] = line.split(/\s+/);
    if (!pattern) continue;
    const re = globToRegExp(normalizePath(pattern));
    for (const a of attrs) {
      if (a === 'linguist-generated' || a === 'linguist-generated=true') out.generated.push(re);
      else if (a === '-linguist-generated' || a === 'linguist-generated=false') out.notGenerated.push(re);
      else if (a === 'linguist-vendored' || a === 'linguist-vendored=true') out.vendored.push(re);
      else if (a === 'linguist-documentation' || a === 'linguist-documentation=true') out.documentation.push(re);
    }
  }
  return out;
}

export function baseClasses(path: string): FileClass[] {
  const classes = new Set<FileClass>();
  if (isLockfile(path)) classes.add('lockfile');
  else if (isManifest(path)) classes.add('manifest');
  if (vendoredRoot(path)) classes.add('vendored');
  if (generatedByName(path) || buildOutputDir(path)) classes.add('generated');
  const lang = languageOf(path);
  if (isTestPath(path)) classes.add('test');
  if (isCodeLanguage(lang) && !classes.has('test')) classes.add('source');
  if (!classes.size) {
    if (isDocsPath(path)) classes.add('docs');
    else if (CONFIG_EXT.has(extname(path)) || basename(path).startsWith('.')) classes.add('config');
  }
  return [...classes];
}
