import { DossierView, parseView } from '@/components/DossierView';
import { Footer, TopBar } from '@/components/ui';
import { sampleDossier } from '@/lib/sample';
import { currentUser } from '@/lib/session';
import { dossierDigest } from '@acquicode/engine';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Sample dossier (demo data)' };

export default async function Sample({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [params, user, d] = await Promise.all([searchParams, currentUser(), sampleDossier()]);
  return (
    <>
      <TopBar signedIn={!!user} />
      <main className="wrap" style={{ paddingTop: '2rem' }}>
        <span className="banner-demo">Demo data: synthetic company</span>
        <h1>{d.title}</h1>
        <p className="muted narrow">
          Meridian Systems does not exist. Its repository is generated by a script with deliberately planted problems (contractors without agreements, a live-looking key, copyleft dependencies,
          contradictory AI attribution, a vulnerable CI workflow) and then analysed by the same engine customers use. Digest <code>{dossierDigest(d).slice(0, 24)}…</code>
        </p>
        <DossierView d={d} view={parseView(params.view)} base="/sample" downloads="/api/sample/download" />
      </main>
      <Footer />
    </>
  );
}
